name: CI/CD
on:
  push
  pull_request
  schedule:
  - cron: "0 0 * * *"
jobs:
  deploy:
    name: Deploy to Github Pages
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: denoland/setup-deno@main
        with:
          deno-version: "1.9.2"
      - uses: actions/checkout@v2
      - name: build
        run: |
          deno install --unstable -A -f -n aleph https://deno.land/x/aleph@v0.3.0-alpha.31/cli.ts
          export PATH="/home/runner/.deno/bin:$PATH"
          aleph build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: dist
