name: CI/CD
on: [ push, pull_request ]
jobs:
  deploy:
    name: Deploy to Github Pages
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/setup-deno@v2.3.0
      - uses: actions/checkout@v2
      - name: build
        run: |
          deno install --unstable -A -f -n aleph https://deno.land/x/aleph@v0.3.0-alpha.31/cli.ts
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: dist
