name: CI/CD
on:
  push:
    branches:
      - main
  schedule:
  - cron: '0 0 * * *'
jobs:
  deploy:
    name: Deploy to Github Pages
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: denoland/setup-deno@main
        with:
          deno-version: "1.28.3"
      - uses: actions/checkout@v2
      - name: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export PATH="/home/runner/.deno/bin:$PATH"
          deno task generate
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: dist
